version: "3.2"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - python-postgres
    # expose:
    #   - 5432
    # ports:
    #   - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    environment:
      - TEST="travis"
    build: .
    ports:
      - 5000:5000
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - python-postgres

networks:
  python-postgres: {}


